# Generated by Django 6.0.5 on 2026-05-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='students/default.jpg', upload_to='students/'),
            preserve_default=False,
        ),
    ]
